name: Publish to GitHub Packages

on:
  release:
    types: [published]
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 

      - name: Set up JDK 11
        uses: actions/setup-java@v4 
        with:
          java-version: '11' 
          distribution: 'temurin' 
          cache: 'gradle' 

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew 

      - name: Publish package
        run: ./gradlew clean build shadowJar publish
        env:
          USERNAME: ${{ github.actor }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}